/home/kevin/Documents/Projects/hsdt-testing/.env/lib/python3.13/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Evaluating hsdt.hsdt.hsdt
On noise_gaussian_30
With models/hsdt_m_gaussian.pth
  0%|          | 0/4 [00:00<?, ?it/s]noise_gaussian_30:   0%|          | 0/4 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/kevin/Documents/Projects/hsdt-testing/hsirun/test.py", line 190, in <module>
    main(args, logdir)
    ~~~~^^^^^^^^^^^^^^
  File "/home/kevin/Documents/Projects/hsdt-testing/hsirun/test.py", line 145, in main
    eval(net, loader, testset, join(logdir, testset), args.clamp, args.bandwise)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevin/Documents/Projects/hsdt-testing/hsirun/test.py", line 48, in eval
    outputs = net(inputs)
  File "/home/kevin/Documents/Projects/hsdt-testing/.env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/kevin/Documents/Projects/hsdt-testing/.env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kevin/Documents/Projects/hsdt-testing/hsdt/hsdt/arch.py", line 130, in forward
    out = self.head(xs[0])
  File "/home/kevin/Documents/Projects/hsdt-testing/.env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/kevin/Documents/Projects/hsdt-testing/.env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kevin/Documents/Projects/hsdt-testing/.env/lib/python3.13/site-packages/torch/nn/modules/container.py", line 240, in forward
    input = module(input)
  File "/home/kevin/Documents/Projects/hsdt-testing/.env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/kevin/Documents/Projects/hsdt-testing/.env/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kevin/Documents/Projects/hsdt-testing/hsdt/hsdt/sepconv.py", line 89, in forward
    return x1 + x2
           ~~~^~~~
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.48 GiB. GPU 0 has a total capacity of 3.69 GiB of which 428.56 MiB is free. Including non-PyTorch memory, this process has 3.24 GiB memory in use. Of the allocated memory 3.16 GiB is allocated by PyTorch, and 4.10 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
noise_gaussian_30:   0%|          | 0/4 [00:01<?, ?it/s]
